import type { Metadata } from "next";
import "./globals.css";
import Header from "./ui/components/Header";
import localFont from 'next/font/local'

export const metadata: Metadata = {
  title: "mrnet - категорически новый интернет для бизнеса",
  description: "Generated by create next app",
};


const GratoGrotesk = localFont({
  src: [
    {
      path: '../public/fonts/Grato-Grotesk-Light-Web.woff',
      weight: '300',
      style: 'normal',

    },
    {
      path: '../public/fonts/Grato-Grotesk-Medium-Web.woff',
      weight: '500',
      style: 'normal',

    },
    {
      path: '../public/fonts/Grato-Grotesk-Regular-Web.woff',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/Grato-Grotesk-Bold-Web.woff',
      weight: '800',
      style: 'normal',
    },
  ],
  variable: '--font-GratoGrotesk',
})


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${GratoGrotesk.variable} antialiased bg-black text-white`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
